### ISSUE TITLE
Possible explanation about the transformation types

### ISSUE THREAD

**Issue by karoush1** [Priw8/priw8.github.io#5]
At `/content/modding/transforms.md`, the section `Transfomation types` mentions:

> The transformation type is a number that's always a power of 2 for no apparent reason (thanks ZUN).

This is probably because he is using [bit fields/masks](https://en.wikipedia.org/wiki/Bit_field) as the values of the transformations. So if `do_nothing=0` and `accelerate=1`, and he wanted to accelerate the bullet, he would apply 1 to the field `accelerate`.

Why didn't he use numbers or enums? No idea, ask God himself.

Also, this could already be addressed, but I don't have access to the transformation table to get a better view of the function.

**Comment by ExpHP** [comment]
Yeah, basically, the game just ORs together the numbers of all of the transformations that are currently have some pending effect onto a single field, and later when it is updating the state associated with each transformation type, it only updates the ones whose bits are active.  There's obviously other ways to achieve this (and I don't get why the argument to etEx isn't just an integer for use in a left shift), but... yeah.

(amusing note: the reason why bit 28 is reserved is because the game puts the sound effect flag there)
